### ISSUE TITLE
Unsorted "feature" still existing?

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster-lib#184]
Dear all, 

I haven't yet had the chance to test the new Hamster on Ubuntu 16.04 as I couldn't find any installable deb package or PPA repository. 

However, coming from the old Hamster, I was wondering if the "unsorted feature" is still existing in the new Hamster version and if so, what is its exact use from a user perspective?

![image](https://cloud.githubusercontent.com/assets/170947/16806438/cb0a6dcc-4914-11e6-8542-84bc88ec8565.png)

Thankfully,

~Robert

**Comment by elbenfreund** [comment]
Im not sure I understand the exact question but maybe the following provides a starting point.

``hamster-lib`` allows activities to belong to 0 or 1 category. If stored in the backend either a pointer to the category or a ``null`` value will be stored.
When retrieved and displayed to the user, an activity without an category could indicate that by various ways: just ``None`` or ``null`` or any other string...
legacy hamster allowed to store a half-hardcoded string ``unsorted_localized`` that would be used whenever such an activity without a category associated would be displayed.

Thats for legacy hamster. ``hamster-lib`` represents activies, categories and facts as fully qualified python class instances. As such ``category`` attribute of an ``Activity`` instance (``Activity.category``) would have the python 'value' None assigned. As far as ``hamster-lib`` is concerned this is where the story ends. It will be up to the individual client to decide how to render/represent this information.
However, it seems unlikely that there is any need for any special treatment by the client. They should be able to just render a string of their choosing, potentially employing their i18n solution of choice.

Did this help at all? If not, could you try another go at your question?

**Comment by orschiro** [comment]
Dear Eric,

Thank you! I think it did help, yes.

So, unsorted is being displayed if no category had been assigned to a task. 

That was the confusing point as in the old hamster, I can't find any way to assign a category to a new task. 

![image](https://cloud.githubusercontent.com/assets/170947/17030333/4a41c152-4f6f-11e6-9bc5-fde338eb3b3c.png)

~Robert

**Comment by elbenfreund** [comment]
It has been **ages** since I last used ``hamster-applet`` and i do not have a working version easily available. But wasn't there a seperate (preferences?) dialog where you could manage activities and assign them to categories?

**Comment by orschiro** [comment]
Yes, you're right. Thanks for your great help!

Warmly,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/17035731/469d772a-4f89-11e6-872e-d1b026d4c87f.png)
